# Site settings
author: Roy
title: Why did I decided to study Software Engineering?
header-img: img/home-bg.png
email: royguzrod@gmail.com
copyright_name: Roy
description: > # this means to ignore newlines until "baseurl:"
  Reasons to study Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rfgr87

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
