# Site settings
author: Roy F Guzman Rodriguez
title: 
header-img: img/home-bg.png
email: royguzrod@gmail.com
copyright_name: Roy F Guzman Rodriguez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rfgr87

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
